# Generated by Django 3.2.4 on 2021-11-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vedio',
            field=models.FileField(blank=True, null=True, upload_to='Category/subCategory/products/'),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='sub_category_image',
            field=models.ImageField(upload_to='Category/subCategory/'),
        ),
    ]
