# Generated by Django 3.2.4 on 2021-11-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20211123_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vedio',
            field=models.FileField(blank=True, default='', null=True, upload_to='products/'),
        ),
    ]
